# This file is auto-generated by scripts/gen_protocol.py.
# Do not edit manually — edit scripts/rpc_methods.yaml and re-run.

"""RPC method name constants and event ID mappings.

All Connection.call() invocations use these constants — no literal strings.
"""

from __future__ import annotations


class RpcMethod:
    """String constants for every RPC method name."""

    # Handshake methods
    HELLO = "hello"

    # Dimension methods
    ATTACH_DIMENSION = "attach_dimension"
    CREATE_DIMENSION = "create_dimension"
    CREATE_DIMENSION_ITEM = "create_dimension_item"
    DELETE_DIMENSION = "delete_dimension"
    DELETE_DIMENSION_ITEMS = "delete_dimension_items"
    DETACH_DIMENSION = "detach_dimension"
    DIMENSION_EFFECTIVE_ORDER = "dimension_effective_order"
    DIMENSION_EFFECTIVE_ORDER_WINDOW = "dimension_effective_order_window"
    DIMENSION_OUTLINE = "dimension_outline"
    MOVE_VIEW_DIMENSION = "move_view_dimension"
    RENAME_DIMENSION = "rename_dimension"
    RENAME_DIMENSION_ITEM = "rename_dimension_item"
    REQUIRE_DIMENSION = "require_dimension"
    SET_DIMENSION_ITEM_ORDER = "set_dimension_item_order"
    VIEW_PAGE_DIMENSIONS = "view_page_dimensions"

    # Cube methods
    ATTACH_DIMENSION = "attach_dimension"
    CREATE_CUBE = "create_cube"
    DELETE_CUBE = "delete_cube"
    DETACH_DIMENSION = "detach_dimension"
    FIND_CUBE_BY_ID = "find_cube_by_id"
    FIND_CUBE_BY_NAME = "find_cube_by_name"
    HAS_SYSTEM_GRAPH_CUBES = "has_system_graph_cubes"
    LIST_CUBE_IDS = "list_cube_ids"
    RENAME_CUBE = "rename_cube"
    REQUIRE_CUBE_BY_ID = "require_cube_by_id"
    RESOLVE_CUBE_ID_BY_NAME = "resolve_cube_id_by_name"
    RULE_COUNTS_FOR_CUBE = "rule_counts_for_cube"

    # Rule methods
    APPLY_RULE_BATCH = "apply_rule_batch"
    DELETE_RULE = "delete_rule"
    DELETE_RULE_ANCHORED = "delete_rule_anchored"
    EVALUATE_RULE = "evaluate_rule"
    EXPAND_RULES = "expand_rules"
    FIND_ANCHORED_RULE = "find_anchored_rule"
    FIND_RULE = "find_rule"
    RESET_RULE_EVAL_PROFILE = "reset_rule_eval_profile"
    RULE_COUNTS_FOR_CUBE = "rule_counts_for_cube"
    RULE_EVAL_PROFILE = "rule_eval_profile"
    SET_RULE = "set_rule"
    SET_RULE_ANCHORED = "set_rule_anchored"
    SET_RULE_ANCHORED_BY_ADDR = "set_rule_anchored_by_addr"
    SET_RULE_ORDER = "set_rule_order"
    UPDATE_CELL_RULE = "update_cell_rule"
    UPDATE_RULE = "update_rule"
    UPDATE_RULE_FULL = "update_rule_full"

    # Cell methods
    ADDR_TO_CELL_REF = "addr_to_cell_ref"
    BATCH_SET_CELL_DATA = "batch_set_cell_data"
    CELL_VALUE_FOR_VIEW_RC = "cell_value_for_view_rc"
    CLEAR_CELL_HARDVALUE = "clear_cell_hardvalue"
    EVALUATE_CELL = "evaluate_cell"
    EVALUATE_CELLS = "evaluate_cells"
    GET_CACHED_CELL_VALUE = "get_cached_cell_value"
    GET_CELL_VALUE = "get_cell_value"
    GET_RANGE = "get_range"
    RESOLVE_CELL_META = "resolve_cell_meta"
    SET_CELL_HARDVALUE = "set_cell_hardvalue"
    SET_CELL_HARDVALUE_BY_ADDR = "set_cell_hardvalue_by_addr"
    SET_RANGE = "set_range"
    UPDATE_CELL_RULE = "update_cell_rule"

    # View methods
    ADDR_FOR_VIEW_IDS = "addr_for_view_ids"
    CELL_VALUE_FOR_VIEW_RC = "cell_value_for_view_rc"
    CREATE_DEFAULT_VIEW = "create_default_view"
    CREATE_VIEW = "create_view"
    LIST_VIEWS = "list_views"
    MOVE_VIEW_DIMENSION = "move_view_dimension"
    REQUIRE_VIEW = "require_view"
    RESOLVE_DEFAULT_VIEW = "resolve_default_view"
    SET_VIEW_AXES = "set_view_axes"
    SET_VIEW_LAYOUT = "set_view_layout"
    VIEW_COL_COUNT = "view_col_count"
    VIEW_COL_DIM_IDS = "view_col_dim_ids"
    VIEW_COL_HEADER = "view_col_header"
    VIEW_COL_ITEMS = "view_col_items"
    VIEW_COL_KEYS = "view_col_keys"
    VIEW_PAGE_DIM_IDS = "view_page_dim_ids"
    VIEW_PAGE_DIMENSIONS = "view_page_dimensions"
    VIEW_ROW_DIM_IDS = "view_row_dim_ids"
    VIEW_ROW_ITEMS = "view_row_items"
    VIEW_ROW_KEYS = "view_row_keys"

    # Group/outline methods
    CREATE_AGGREGATE_ITEM = "create_aggregate_item"
    CREATE_GROUP = "create_group"
    DELETE_GROUP_NODE = "delete_group_node"
    ENSURE_GROUP_IN_GRAPH = "ensure_group_in_graph"
    MOVE_ITEMS_TO_GROUP = "move_items_to_group"
    MOVE_NODES = "move_nodes"
    PLACE_ITEM_NODES = "place_item_nodes"
    RENAME_GROUP_NODE = "rename_group_node"
    REORDER_NODES = "reorder_nodes"
    UNGROUP_ITEMS = "ungroup_items"

    # Recompute methods
    BOOTSTRAP_DEP_GRAPH = "bootstrap_dep_graph"
    CLEAR_CACHES = "clear_caches"
    DIMENSION_EFFECTIVE_ORDER = "dimension_effective_order"
    DIMENSION_EFFECTIVE_ORDER_WINDOW = "dimension_effective_order_window"
    DIRTY_COUNT = "dirty_count"
    DIRTY_KEYS = "dirty_keys"
    GET_DEP_TRACKING = "get_dep_tracking"
    HAS_DIRTY_NODES = "has_dirty_nodes"
    MULTITHREAD_RECOMPUTE_CONFIG = "multithread_recompute_config"
    RECALCULATE_ALL = "recalculate_all"
    RECOMPUTE_DIRTY = "recompute_dirty"
    RECOMPUTE_WORKSPACE = "recompute_workspace"
    RECOMPUTE_WORKSPACE_EXPAND = "recompute_workspace_expand"
    SET_DEP_TRACKING = "set_dep_tracking"

    # Undo/redo methods
    CAN_REDO = "can_redo"
    CAN_UNDO = "can_undo"
    GET_REDO_DESCRIPTION = "get_redo_description"
    GET_UNDO_DESCRIPTION = "get_undo_description"
    REDO = "redo"
    UNDO = "undo"

    # Query/diagnostic methods
    ANALYZE_DETACH = "analyze_detach"
    ANALYZE_DIM_DELETION = "analyze_dim_deletion"
    ANALYZE_ITEM_DELETION = "analyze_item_deletion"
    DEPENDENCY_METRICS = "dependency_metrics"
    EVALUATE_ALL_BRUTEFORCE = "evaluate_all_bruteforce"
    GET_STATS = "get_stats"
    GET_WORKSPACE = "get_workspace"
    LIST_DEPENDENTS = "list_dependents"
    LIST_PRECEDENTS = "list_precedents"
    LOAD_WORKSPACE_MSGPACK = "load_workspace_msgpack"
    RECOMPUTE_WORKSPACE = "recompute_workspace"
    RECOMPUTE_WORKSPACE_EXPAND = "recompute_workspace_expand"
    RESET_PROFILER = "reset_profiler"
    RESET_RULE_EVAL_PROFILE = "reset_rule_eval_profile"
    RULE_EVAL_PROFILE = "rule_eval_profile"
    TRACE_CALCULATION_FLOW = "trace_calculation_flow"
    TRACE_CIRCULAR_REFERENCES = "trace_circular_references"

    # Lifecycle methods
    ADDR_FOR_VIEW_IDS = "addr_for_view_ids"
    ENSURE_GROUP_IN_GRAPH = "ensure_group_in_graph"
    GET_PAGE_ITEM_ID = "get_page_item_id"
    HAS_SYSTEM_GRAPH_CUBES = "has_system_graph_cubes"
    LOAD_WORKSPACE_MSGPACK = "load_workspace_msgpack"
    RESOLVE_CUBE_ID_BY_NAME = "resolve_cube_id_by_name"
    RESOLVE_ITEM_NODE_ID = "resolve_item_node_id"

    # Legacy server methods
    EVALUATE_EXPRESSION = "evaluate_expression"
    EVALUATE_RULE = "evaluate_rule"
    EXPAND_RULES = "expand_rules"
    GET_STATS = "get_stats"
    PING = "ping"
    RECOMPUTE_WORKSPACE = "recompute_workspace"
    RECOMPUTE_WORKSPACE_EXPAND = "recompute_workspace_expand"
    VERSION = "version"


# Event ID → Python message bus topic mapping.
# The wire protocol uses integer event IDs; RemoteEngine maps them to
# string topics for the Python message bus.
_EVENT_ID_TO_TOPIC: dict[int, str] = {
    1: "event.dimension.created",
    2: "event.dimension.deleted",
    3: "event.dimension.renamed",
    4: "event.cube.created",
    5: "event.cube.deleted",
    6: "event.rule.set",
    7: "event.cell.value_changed",
    8: "event.dimension_item.created",
    9: "event.dimension_item.deleted",
    10: "event.dimension_item.renamed",
    11: "event.cube_dimension.attached",
    12: "event.cube_dimension.detached",
    13: "event.cube.renamed",
    14: "event.rule.deleted",
    15: "event.rule.updated",
    16: "event.rule.order_changed",
    17: "event.view.created",
    18: "event.view.deleted",
    19: "event.view.axes_changed",
    20: "event.view.layout_changed",
    21: "event.group.created",
    22: "event.group.deleted",
    23: "event.group.node_moved",
    24: "event.workspace.replaced",
}

