"""Version accessor for OpenM components.

Combines the manual root version from version-manual.txt with the build
suffix from version.txt (generated by run_engine_tests.sh) in the project
root.
"""
from __future__ import annotations

from pathlib import Path


_VERSION_FILE_NAMES = ("version-manual.txt", "version.txt")


def _find_version_files() -> tuple[Path | None, Path | None]:
    """Locate version-manual.txt and version.txt for this package or cwd."""
    here = Path(__file__).resolve().parent.parent
    candidates = [
        here / "version-manual.txt",
        here / "version.txt",
        Path.cwd() / "version-manual.txt",
        Path.cwd() / "version.txt",
    ]
    manual_path: Path | None = None
    suffix_path: Path | None = None
    for p in candidates:
        if p.name == "version-manual.txt" and p.exists() and manual_path is None:
            manual_path = p
        elif p.name == "version.txt" and p.exists() and suffix_path is None:
            suffix_path = p
    return manual_path, suffix_path


def om_version() -> str:
    """Return the combined version: "<manual>-<build-suffix>".

    Returns "unknown" if neither version file is found.
    """
    manual_path, suffix_path = _find_version_files()
    if manual_path is None and suffix_path is None:
        return "unknown"
    try:
        parts = []
        if manual_path is not None:
            parts.append(manual_path.read_text(encoding="utf-8").strip())
        if suffix_path is not None:
            parts.append(suffix_path.read_text(encoding="utf-8").strip())
        return "-".join(p for p in parts if p)
    except Exception:
        return "unknown"
